#docker file for eureka server

FROM openjdk:12

MAINTAINER jlam <joey.cm.lam@gmail.com>

ADD HierarchyProvider-1.0-SNAPSHOT.jar HierarchyProvider-1.0-SNAPSHOT.jar

EXPOSE 8081

ENTRYPOINT java -jar HierarchyProvider-1.0-SNAPSHOT.jar

